### ISSUE TITLE
Changing color palette?

### ISSUE THREAD

**Issue by viymak** [GSA/code-gov-style#8]
I'd like to reuse this with my own color palette. How would I do that?

**Comment by DanielJDufour** [comment]
Thank you for your question.  Currently, you have to edit the SASS variables in [_variables.scss](https://github.com/GSA/code-gov-style/blob/master/_sass/_variables.scss).  For example, if you want to change the teal color on the site to maroon, you'd have to change `$brand-teal` to `$brand-maroon` in that file, but also replace `$brand-teal` with `$brand-maroon` in all the other files in the [sass folder](https://github.com/GSA/code-gov-style/tree/master/_sass)

We can explore creating a functional palette, where the variables are named by their purpose rather than color.  In that case, we'd probably have fewer variables, you'd have to edit, such as (1) `primary-color`, (2) `secondary-color`, (3) `accent-color`.  We'll keep this ticket open for now and updated as things change.

**Comment by saracope** [comment]
Closing this one out as there are no plans to add any color variable enhancements in the current roadmap.
